# Generated by Django 4.0.4 on 2022-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('solar', 'PV'), ('wind', 'WT')], default='solar', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['value'],
            },
        ),
    ]
